#!/usr/bin/env python3
"""build/manifest.json -> data/manifest.js (the site loads data as plain scripts so it works from file://)."""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
m = json.load(open(os.path.join(ROOT, "build", "manifest.json")))
out = {}
for tag, qs in m.items():
    for q in qs:
        out[f"{tag}-q{q['q']}"] = {"title": q["title"], "stem": q["stem"]}
        for it in q["items"]:
            out[f"{tag}-q{q['q']}.{it['item']}"] = {"pts": it["pts"], "bonus": it["bonus"], "q": it["q"], "sol": it["sol"]}
with open(os.path.join(ROOT, "data", "manifest.js"), "w") as f:
    f.write("// generated by tools/build_data.py — do not edit\nwindow.MANIFEST = " + json.dumps(out, ensure_ascii=False, indent=0) + ";\n")
print(len(out), "entries")
